// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: refresh-tokens.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createRefreshToken = `-- name: CreateRefreshToken :one
INSERT INTO refresh_tokens (token, created_at, updated_at, user_id, expires_at, revoked_at)
VALUES (
    $1,
    NOW(),
    NOW(),
    $2,
    $3,
    NULL
)
RETURNING token, created_at, updated_at, user_id, expires_at, revoked_at
`

type CreateRefreshTokenParams struct {
	Token     string
	UserID    uuid.UUID
	ExpiresAt time.Time
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error) {
	row := q.db.QueryRowContext(ctx, createRefreshToken, arg.Token, arg.UserID, arg.ExpiresAt)
	var i RefreshToken
	err := row.Scan(
		&i.Token,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const getUserFromRefreshToken = `-- name: GetUserFromRefreshToken :one
SELECT refresh_tokens.token, refresh_tokens.created_at, refresh_tokens.updated_at, refresh_tokens.user_id, refresh_tokens.expires_at, refresh_tokens.revoked_at, users.id, users.created_at, users.updated_at, users.email, users.hashed_password 
FROM refresh_tokens 
INNER JOIN users 
ON users.id = refresh_tokens.user_id
WHERE token = $1 AND revoked_at IS NULL
`

type GetUserFromRefreshTokenRow struct {
	Token          string
	CreatedAt      time.Time
	UpdatedAt      time.Time
	UserID         uuid.UUID
	ExpiresAt      time.Time
	RevokedAt      sql.NullTime
	ID             uuid.UUID
	CreatedAt_2    time.Time
	UpdatedAt_2    time.Time
	Email          string
	HashedPassword string
}

func (q *Queries) GetUserFromRefreshToken(ctx context.Context, token string) (GetUserFromRefreshTokenRow, error) {
	row := q.db.QueryRowContext(ctx, getUserFromRefreshToken, token)
	var i GetUserFromRefreshTokenRow
	err := row.Scan(
		&i.Token,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.ID,
		&i.CreatedAt_2,
		&i.UpdatedAt_2,
		&i.Email,
		&i.HashedPassword,
	)
	return i, err
}

const setRevokedAt = `-- name: SetRevokedAt :exec
UPDATE refresh_tokens
SET revoked_at = $2, updated_at = NOW()
WHERE token = $1
`

type SetRevokedAtParams struct {
	Token     string
	RevokedAt sql.NullTime
}

func (q *Queries) SetRevokedAt(ctx context.Context, arg SetRevokedAtParams) error {
	_, err := q.db.ExecContext(ctx, setRevokedAt, arg.Token, arg.RevokedAt)
	return err
}
